# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('track', models.FileField(upload_to=b'tracks')),
                ('timestamp', models.DateTimeField()),
                ('geojson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.GeoJson')),
            ],
        ),
    ]
