# Generated by Django 2.1.1 on 2018-09-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='geojson',
        ),
        migrations.DeleteModel(
            name='GeoJson',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
