# Generated by Django 2.1.1 on 2018-09-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_remove_track'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewTrack',
            new_name='Track',
        ),
    ]
